In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

# Tensors

A Tensor is a multi-dimensional array that represent data in n-dimensional space. \
Tensors can be though of as containers for numerical data, just like arrays or matrices, but generalized to any number of dimensions.


https://docs.google.com/document/d/1e3xvh0N8DTJ2YVYB-p-4_J4wxkXf4CSpo9Pa8SMtVQI/edit?tab=t.sf1selmw9ju3

### Scalar -  0-D

In [3]:
# scalar 0 D
scalar = torch.tensor(5)
print(scalar)

tensor(5)


### Vector -  1-D

In [5]:
# Vector 1 D
vector = torch.tensor([1.0, 2.0, 3.0])
print(vector)

tensor([1., 2., 3.])


### Matrix -  2-D

In [6]:
# Matrix 2 D
matrix = torch.tensor( [[1,2], [3, 4] ] )
print(matrix)

tensor([[1, 2],
        [3, 4]])


### High Dimensional Tensor - n-D

In [7]:
# 3D Tensor
tensor3d = torch.tensor( [[ [255, 0, 0], [0, 255, 0], [0, 0, 255] ]] )
print(tensor3d)

tensor([[[255,   0,   0],
         [  0, 255,   0],
         [  0,   0, 255]]])
